openapi: 3.0.3
info:
  version: 1.0.0
  title: SMU_UMC_MINI_PROJECT - Swagger
  description: SMU_UMC_MINI_PROJECT - Swagger입니다.
paths:
  /api/posts/get:
    get:
      tags:
        - Posts
      summary: 게시글 전체 조회
      description: 게시글 전체 조회하기
      responses:
        '200':
          description: 게시글 전체 조회 성공!
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: '60d21b4667d0d8992e610c85'
                    title:
                      type: string
                      example: '첫번째 게시글'
                    content:
                      type: string
                      example: '이것은 첫번째 게시글의 내용입니다.'
                    createdAt:
                      type: string
                      format: date-time
                      example: '2023-06-19T12:34:56Z'
                    updatedAt:
                      type: string
                      format: date-time
                      example: '2023-06-19T12:34:56Z'
        '500':
          description: 서버 오류
  /api/posts/get/{post_id}:
    get:
      tags:
        - Posts
      summary: 게시글 1개 조회
      description: 게시글 ID로 게시글 1개 조회하기
      parameters:
        - name: post_id
          in: path
          required: true
          description: 조회할 게시글의 ID
          schema:
            type: string
      responses:
        '200':
          description: 게시글 1개 조회 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: '60d21b4667d0d8992e610c85'
                  title:
                    type: string
                    example: '첫번째 게시글'
                  content:
                    type: string
                    example: '이것은 첫번째 게시글의 내용입니다.'
                  createdAt:
                    type: string
                    format: date-time
                    example: '2023-06-19T12:34:56Z'
                  updatedAt:
                    type: string
                    format: date-time
                    example: '2023-06-19T12:34:56Z'
        '404':
          description: 게시글을 찾을 수 없음
        '500':
          description: 서버 오류
  /api/posts/patch/{post_id}:
    patch:
      tags:
        - Posts
      summary: 게시글 수정
      description: 게시글 ID로 게시글 수정하기
      parameters:
        - name: post_id
          in: path
          required: true
          description: 조회할 게시글의 ID
          schema:
            type: string
        - name: signIn
          in: body
          required: true
          schema:
            properties:
              title:
                type: string
                description: 게시글 제목
                example: 안녕하세요
              content:
                type: string
                description: 게시글 내용
                example: 야호야호야호야호야호야호야호야호야호야호야호야호야호야호
          responses:
          '200':
            description: 회원 가입 성공!
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 200
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 2000
                message:
                  type: string
                  example: 'success!'
                data:
                  type: object
                  example:
                    { 'email': 'swaggerTest@mail.com', 'name': 'swagger' }

          '400':
            description: 잘못된 요청
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 400
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON001
                message:
                  type: string
                  example: 잘못된 요청입니다
          '500':
            description: 서버 에러
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 500
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON000
                message:
                  type: string
                  example: 서버 에러, 관리자에게 문의 바랍니다.
  /api/posts/create:
    post:
      tags:
        - Posts
      summary: 게시글 생성
      description: 게시글 생성하기
      parameters:
        - name: Posts
          in: body
          required: true
          schema:
            properties:
              title:
                type: string
                description: 게시글 제목
              content:
                type: string
                description: 게시글 내용
      responses:
        '201':
          description: 게시글 생성 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: '60d21b4667d0d8992e610c89'
                  title:
                    type: string
                    example: '새로운 게시글 제목'
                  content:
                    type: string
                    example: '이것은 새로운 게시글의 내용입니다.'
                  createdAt:
                    type: string
                    format: date-time
                    example: '2023-06-19T12:34:56Z'
                  updatedAt:
                    type: string
                    format: date-time
                    example: '2023-06-19T12:34:56Z'
        '500':
          description: 서버 오류
  /api/posts/delete/{post_id}:
    delete:
      tags:
        - Posts
      summary: 게시글 삭제
      description: 게시글 ID로 게시글 삭제하기
      parameters:
        - name: post_id
          in: path
          required: true
          description: 삭제할 게시글의 ID
          schema:
            type: string
      responses:
        '200':
          description: 게시글 삭제 성공!
        '404':
          description: 게시글을 찾을 수 없음
        '500':
          description: 서버 오류
